---
output:
  pdf_document: default
  html_document: default
  word_document: default
---

STAT430 Homework #6: Due Friday, March 29, 2019 (after break). 
========================================================

#### Name: 

*********************************************************************************
0. We will continue with **Chapter 8** on estimation.  You should have read **Sections 8.1-8.4** on point estimation; please continue with **Sections 8.5-8.10** on interval estimation and related topics.   



1. Complete **Exercise 8.56** of the text.

*********************************************************************************
  
**Answer:**



*********************************************************************************
2. Complete **Exercise 8.60** of the text.  In part (b), "What conclusions can you draw?", think about what you can conclude if your temperature is above 98.6.

*********************************************************************************

**Answer:**



*********************************************************************************

3. In class, we considered the Physician's Health Study, in which a large number of physicians were randomized to receive a treatment of an aspirin every other day or a placebo every other day.  They were followed for five years, and the number of heart attacks in each group was recorded.   Among the $n_1 = 11034$ physicians taking placebo, there were 189 heart attacks, and among the  $n_2 = 11037$ taking aspirin, there were 104  heart attacks.  Give a point estimate for the log(relative risk) and an approximate 99% confidence interval.  Then exponentiate your point estimate and the endpoints of your CI to give an approximate 99% confidence interval for relative risk.  Interpret your point estimate and confidence interval.   

*********************************************************************************

**Answer:**


 
*********************************************************************************

4. In a previous homework, you used the delta method to determine the  approximate distribution of the estimated log-odds for large sample size, where the odds of success 
are defined as 
\[
\frac{\mbox{probability of success}}{\mbox{probability of failure}}
\]
Now suppose that $Y_1\sim$   Binomial$(n_1,p_1)$, independent of $Y_2\sim$   Binomial$(n_2,p_2)$, where both $n_1$ and $n_2$ are large.  The **odds ratio** is defined as 
\[
\frac{\mbox{odds in group 1}}{\mbox{odds in group 2}}=\frac{p_1/(1-p_1)}{p_2/(1-p_2)}.
\]

4(a).  Consider the log-odds ratio,
\[
\theta=\ln\left(\frac{p_1/(1-p_1)}{p_2/(1-p_2)}\right)=\ln\left(\frac{p_1}{1-p_1}\right)-\ln\left(\frac{p_2}{1-p_2}\right).
\]
Construct an approximate $(1-\alpha)$ 100% confidence interval for the log-odds ratio. 


*********************************************************************************

**Answer:**



*********************************************************************************

4(b).  The *British Medical Journal* reported the following data for 114 patients with spondyloarthropathies (a kind of joint disease) and 334 patients without spondyloarthropathies.  In the "with" group, 54 had the ABO secretor state (a genetic feature), and in the "without" group, 89 had the ABO secretor state.  The journal reported an odds ratio of 2.48 and a 95% confidence interval of $[1.59,3.85]$.   Use your computed confidence interval from 4(a) to reproduce the journal's reported confidence interval. 


*********************************************************************************

**Answer:**



************************************************************************************************

5. In baseball, a *complete game* is one in which a single pitcher does all of the pitching for one team, without the benefit of a relief pitcher.  A *complete game shutout* is one in which that pitcher allows no runs by the opposing team.  Such games are rare.  For the 2016 Major League Baseball (MLB) season, there were 36 complete game shutouts out of 2,427 games played. The dataset `2016_MLB_Pitching.csv` contains pitching statistics for each of the 30 MLB teams for the 2016 season, including the number of complete game shutouts (`cSho`) for each team.  If you put the dataset in a subfolder called `Data` of the homework folder where this markdown file is stored, you can read it as follows:     
```{r}
MLB <- read.csv("Data/2016_MLB_Pitching.csv", header = TRUE) # read in the dataset and call it MLB
head(MLB)        # look at the first few lines of the dataset
table(MLB$cSho)  # table the values of the variable cSho in the MLB dataset
```
This dataset and additional details can be found at  
<https://www.baseball-reference.com/leagues/MLB/2016-standard-pitching.shtml>

We might want to model the number of complete shutouts for each team as Binomial with number of trials equal to number of games played (161 or 162) and some small success probability.  Since the binomial model would involve a large number of trials and a small probability of success, another alternative would be to model the number of complete shutouts per team as $Y_i$ iid Poisson($\lambda$) ($i=1,2,\ldots,30$). Treat the observations as independent, even though this cannot be exactly true (if one team has a complete shutout in a game, then the opposing team certainly did not.) Treat the observations as identically distributed, though this cannot be exactly true either. 

(a). Estimate the target $\lambda$, the mean of the Poisson distribution, with $\hat\lambda=\bar Y=$ sample mean of the $n=30$ observations. 


************************************************************************************************

**Answer:**


************************************************************************************************

(b). Assume that $n=30$ is a large sample, and give an approximate 95% confidence interval for the target, $\lambda$. 


************************************************************************************************

**Answer:**



************************************************************************************************

(c). Under the Poisson model, the probability that a team has exactly zero complete game shutouts is 
\[
\theta=P(Y_i=0)=\frac{\lambda^0e^{-\lambda}}{0!}=e^{-\lambda}.
\]
Give a point estimate of this probability by plugging in $\hat\lambda$.  Then use the approximate 95% CI from (b) and the fact that 
\[
0.95\simeq P\left(\hat\lambda_L\le\lambda\le\hat\lambda_U\right)
\]
to construct an approximate 95% confidence interval for the new target, $\theta$. 


************************************************************************************************

**Answer:**



************************************************************************************************
(d). Use the delta method to derive a 95% confidence interval for the probability that a team has  exactly one complete game shutout under the Poisson model,
\[
\theta=P(Y_i=1)=\frac{\lambda^1e^{-\lambda}}{1!}=\lambda e^{-\lambda}.
\]



************************************************************************************************

**Answer:**



************************************************************************************************

**Optional problems:**  Good optional review problems  are 8.39, 8.43, 8.48 for confidence intervals with a general pivot; and any of 8.57 thru 8.67 for large-sample normal confidence intervals on simple targets like means, proportions, differences of means, and differences of proportions. 

