---
output:
  pdf_document: default
  html_document: default
  word_document: default
---

STAT430 Homework #10: Due Friday, May 3, 2019. 
========================================================

#### Name: 

*********************************************************************************
\newcommand{\prob}{\overset{P}{\to}}

0. We finish **Chapter 9** on estimation and start **Chapter 10** on hypothesis testing.     


1. Each of the following sequences converges in probability to something.  Identify the limit, with a brief justification and any necessary conditions.  

For example: Suppose $Y_1,Y_2,\ldots,Y_n$ are iid $N(\mu,\sigma^2)$.  Then $\bar Y\prob\mu$ by the law of large numbers (LLN) and $1/\bar Y\prob 1/\mu$ by the continuous function result, provided $\mu\ne 0$. 

(1a). $Y_1,Y_2,\ldots,Y_n$ are iid $N(\mu,\sigma^2)$.  What is the limit in probability of 
\[
\frac{\bar Y - 3}{\bar Y + 2}?
\]


*********************************************************************************
  
**Answer:**

$$\frac{\bar Y -3}{\bar Y + 2} \implies \frac{\mu - 3}{\mu + 2}$$


*********************************************************************************


(1b). $Y_1,Y_2,\ldots,Y_n$ are iid Exponential$(\beta)$.  What is the limit in probability of 
\[
\exp\left(\frac{-\bar Y}{\beta}\right)?
\]

*********************************************************************************
  
**Answer:**


$$\exp\left(\frac{-\bar Y}{\beta}\right) \implies \exp\left(\frac{-\beta}{\beta}\right) = \exp(-1)$$


*********************************************************************************


(1c). $Y_1,Y_2,\ldots,Y_n$ are iid Exponential$(\beta)$.  What is the limit in probability of 
\[
\frac{1}{n}\sum_{i=1}^n\exp\left(\frac{-Y_i}{\beta}\right)?
\]
Check your answer via simulation with the following `R` code: 
```{r}
beta <- 5 # mean of exponential, but R uses rate parameterization
set.seed(4302019)
y <- rexp(1000, rate = 1 / beta)
mean(exp(-y / beta))
```
Does the choice of $\beta$ in the code matter?


*********************************************************************************
  
**Answer:**

$$E\left[\exp\left(\frac{-Y_i}{\beta}\right)\right] = \int_0^\infty \exp\left(\frac{-Y_i}{\beta}\right)f(y)dy = \int_0^\infty \exp\left(\frac{-Y_i}{\beta}\right)\left(\frac{1}{\beta}\exp\left(\frac{-Y_i}{\beta}\right)\right)dy$$

$$ = \frac{1}{2}\left(\frac{2}{\beta}\int_0^\infty exp\left(\frac{-2y}{\beta}\right)dy\right) = \frac{1}{2}(1) = 1/2$$



*********************************************************************************

(1d). $Y_1,Y_2,\ldots,Y_n$ are iid Uniform$(0,\theta)$.  What is the limit in probability of
\[
\left(\frac{1}{n}\sum_{i=1}^nY_i\right)^k
\]
for $k=1, 2, 3, \ldots$?  

*********************************************************************************
  
**Answer:**

This is just the mean of Uniform from 0 to $\theta$ to the k, so

$$\left(\frac{\theta}{2}\right)^k$$



*********************************************************************************

(1e). $Y_1,Y_2,\ldots,Y_n$ are iid Uniform$(0,\theta)$.  What is the limit in probability of
\[
\frac{1}{n}\sum_{i=1}^nY_i^k
\]
for $k=1, 2, 3, \ldots$?  Check your answer via simulation when $\theta=2$ (use `Y <- runif(10000, min = 0, max = 2)`) for $k =1,2,3,4$.


*********************************************************************************
  
**Answer:**


This is the $k^{th}$ Moment of the Uniform from 0 to $\theta$, so

$$E\left[Y_i^k\right] = \int_0^\theta y^k/\theta dy = \frac{\theta^k}{k+1}$$


*********************************************************************************************************

2. Complete **Exercise 10.2** of the text.  Use `R` for the probability calculations. 

*********************************************************************************
  
**Answer:**


#### a)

Type I error is when $Y$ is in the Rejection Region when $H_o$ is true.

#### b)

$$\alpha = P(Y \le 12,p= 0.8) = \sum_{i=0}^{12}{20\choose i}(0.8)^i(0.2)^{20-i} = 0.032$$

#### c)

Type II error is when $Y>12$ but $H_o$ is false.

#### d)

$$\beta = P(Y>12, p=0.6) = \sum_{i=13}^{20}{20\choose i}(0.6)^i(0.4)^{20-i} = 0.4159$$

#### e)

$$\beta = P(Y>12, p=0.4) = \sum_{i=13}^{20}{20\choose i}(0.4)^i(0.6)^{20-i} = 0.021$$


*********************************************************************************************************


3. Complete **Exercise 10.3** of the text.  Use `R` for the probability calculations. 


*********************************************************************************
  
**Answer:**

#### a)

$$0.01 = \sum_{i=0}^{c}{20\choose i}(0.8)^i(0.2)^{20-i}$$

So using Wolfram to solve, $c=11$.


#### b)

$$\beta = P(Y>11, p=0.6) = \sum_{i=12}^{20}{20\choose i}(0.6)^i(0.4)^{20-i} = 0.596$$

#### c)


$$\beta = P(Y>11, p=0.4) = \sum_{i=12}^{20}{20\choose i}(0.4)^i(0.6)^{20-i} = 0.057$$



********************************************************************************************************

4. Consider **Exercise 10.20** in the text.  State the **R**esearch question in the context of the problem; the corresponding **A**lternative hypothesis in terms of model parameters;  the **N**ull hypothesis that will be our default in the absence of strong evidence to the contrary; the **T**est statistic used to compare the competing hypotheses; the **D**istribution of the test statistic under the null hypothesis; the statistical **R**esults, obtained by specifying a rejection region with significance level $\alpha-0.01$; and the **C**onclusion in the context of this problem. 

*********************************************************************************
  
**Answer:**


### R:
Is the manufacturer's claim of an average of at least 64 true?

### A:
$H_a$: $\mu < 64$

### N:
$H_0$: $\mu = 64$

### T:
$Z = \frac{\bar X - \mu}{S/\sqrt n}$

### D:
$Z \sim N(0,1)$

### R:
$-1.768 > -2.33 = Z_{\alpha = 0.01}$

### C:
So we would fail to reject $H_0$ which means that the statement made by the manufacturer could be true.

*********************************************************************************************************

5. Consider **Exercise 10.21** in the text.  State the **R**esearch question in the context of the problem; the corresponding **A**lternative hypothesis in terms of model parameters;  the **N**ull hypothesis that will be our default in the absence of strong evidence to the contrary; the **T**est statistic used to compare the competing hypotheses; the **D**istribution of the test statistic under the null hypothesis; the statistical **R**esults, obtained by specifying a rejection region with significance level $\alpha-0.01$; and the **C**onclusion in the context of this problem. 

*********************************************************************************
  
**Answer:**

### R: 
Do the two types of soil differ in average shear strength?

### A:
$H_a$: $\mu_1 \ne \mu_2$

### N:
$H_0$: $\mu_1 = \mu_2$

### T:
$Z = \frac{\mu_1 - \mu_2}{\sqrt{\frac{S_1^2}{n_1} + \frac{S_2^2}{n_2}}} = 3.65$

### D:
$Z \sim N(0,1)$

### R:
$3.65 > 2.58 = Z_{\alpha/2}$

### C:
So we would say that these two soils differ in shear strength and we would reject $H_0$.

  
*********************************************************************************

**Optional problems:**  We will have another homework on hypothesis testing, so there will be additional practice. Look through the problems in 10.2, which focus on definitions and are good to review, and the problems in 10.3, which focus on large-sample hypothesis tests (some of the most common in practice).   

